baseURL: https://kozymacro.com/
title: Kozy Macro - Knight Online Makro - Rise Online Makro
enableRobotsTXT: true
publishdir: docs
theme: default

googleAnalytics: UA-111573294-1

# SEO Optimization
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5

# URL yapısını düzenle
removePathAccents: false

permalinks:
  blog: /blog/:slug/
  videos: /videos/:slug/

defaultContentLanguageInSubdir: false
defaultContentLanguage: tr

params:
  version: v2.5.8.5
  downloadLink: https://storage.googleapis.com/kozy-releases/Download%20Manager.exe
  showNewFeaturesOnTop: false
  paymentMethod: "stripe"
  paymentMethodTr: "shopier"
  # SEO Parameters
  description: "Lightweight, safe and easy to use Knight Online makro. For USKO, Myko, SteamKO, PVP and all servers."
  images: ["assets/img/logo-og.png"]
  logo: "assets/img/logo.png"
  author: "Kozy Macro"

languages:
  tr:
    languageCode: "tr-TR"
    contentDir: "content/tr"
    weight: 1
    languageName: "Türkçe"
    params:
      url: "/"
  en:
    languageCode: "en-US"
    contentDir: "content/en"
    weight: 2
    languageName: "English"
    params:
      url: "/en"
